# Generated by Django 3.2.6 on 2022-04-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(blank=True, default=None)),
                ('nombre', models.CharField(max_length=50)),
                ('universidad', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(choices=[('ES', 'Estudiante'), ('ME', 'Mentor'), ('CE', 'CEO')], max_length=2)),
            ],
        ),
    ]
