# Generated by Django 3.2.6 on 2022-04-01 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_cedula'),
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='place',
            new_name='resultado',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='dateTime',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='value',
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='cita',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
